version: '3.1'

services:
  stats-server:
    build: ./stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      DB_HOST: stats-db
      DB_PORT: 5432
      DB_NAME: stats
      DB_USER: stats
      DB_PASS: stats

  stats-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats

  ewm-service:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      DB_HOST: ewm-db
      DB_PORT: 5432
      DB_NAME: ewmdb
      DB_USER: ewmuser
      DB_PASS: ewmpassword
      STATS_SERVER_URL: http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ewmdb
      POSTGRES_USER: ewmuser
      POSTGRES_PASSWORD: ewmpassword
